import { config } from 'dotenv';

config();

const { PORT, DATABASE_HOST, DATABASE_PORT, DATABASE_LOGIN, DATABASE_PASSWORD, DATABASE_NAME } =
  process.env;

export { PORT, DATABASE_HOST, DATABASE_LOGIN, DATABASE_NAME, DATABASE_PASSWORD, DATABASE_PORT };
